export const SITE_TITLE = 'fonUFAL';
export const SITE_URL = 'https://fonufal.github.io';
export const SITE_DESCRIPTION = 'Grupo de Estudos em Fonética e Fonologia da Universidade Federal de Alagoas';
export const SITE_DESCRIPTION_EN = 'Phonetics and Phonology Research Group at the Federal University of Alagoas (UFAL), Brazil';
export const CONTACT_EMAIL = 'fonufal@fale.ufal.br';
export const INSTAGRAM_URL = 'https://www.instagram.com/fon_ufal';
export const MAILING_LIST_URL = 'https://groups.google.com/g/fonufal';
export const LOGO = '/logo-fonufal.png';
export const OG_IMAGE = '/og-image.png';
